version: 2
jobs:
  deploy-dev:
    docker:
      - image: circleci/node:8.10

    environment: 
        TARGET_ENV: sandpit

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless@latest
            yarn
            sudo apt-get install awscli

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
      
      - run:
          name: Deploy dev application
          command: |
            export ACCOUNT_ID=159220020591
            chmod +x scripts/aws-cli-assumerole.sh
            source scripts/aws-cli-assumerole.sh
            sls deploy --stage ${TARGET_ENV} --region ${AWS_DEFAULT_REGION} --accountId ${ACCOUNT_ID}

  deploy-non-prod:
    docker:
      - image: circleci/node:8.10

    environment: 
        TARGET_ENV: nonprod

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless@latest
            yarn
            sudo apt-get install awscli

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
      
      - run:
          name: Deploy non prod application
          command: |
            export ACCOUNT_ID=211853473677
            chmod +x scripts/aws-cli-assumerole.sh
            source scripts/aws-cli-assumerole.sh
            sls deploy --stage ${TARGET_ENV} --region ${AWS_DEFAULT_REGION}

  deploy-prod:
    docker:
      - image: circleci/node:8.10

    environment: 
        TARGET_ENV: prod

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless@latest
            yarn
            sudo apt-get install awscli

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
      
      - run:
          name: Deploy prod application
          command: |
            export ACCOUNT_ID=985566274543
            chmod +x scripts/aws-cli-assumerole.sh
            source scripts/aws-cli-assumerole.sh
            sls deploy --stage ${TARGET_ENV} --region ${AWS_DEFAULT_REGION}

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-dev:
          filters:
            branches:
              only:
                - master
      - non-prod-approval:
          type: approval
          requires:
            - deploy-dev
          filters:
            branches:
              only:
                - master
      - deploy-non-prod:
          requires:
            - non-prod-approval
          filters:
            branches:
              only:
                - master
      - prod-approval:
          type: approval
          requires:
            - deploy-non-prod
          filters:
            branches:
              only:
                - master
      - deploy-prod:
          requires:
            - prod-approval
          filters:
            branches:
              only:
                - master


