Resources:
  DynamoTableBooking:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.TableName, 'dev-bookings'}
      AttributeDefinitions:
        - AttributeName: ${self:custom.FirstAttributeName, 'bookingId'}
          AttributeType: S
      KeySchema:
        - AttributeName: ${self:custom.FirstAttributeName, 'bookingId'}
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.TableThroughput}
        WriteCapacityUnits: ${self:custom.TableThroughput}
  DynamoTablePreReservation:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.PreReservationTableName, 'dev-bookings-pre-reservation'}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: ttl
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: ttl
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.TableThroughput}
        WriteCapacityUnits: ${self:custom.TableThroughput}
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
